# used https://github.com/PaperMC/Paper/blob/master/.github/ISSUE_TEMPLATE/behavior-bug-or-plugin-incompatibility.yml as template
name: Ask Question
description: Ask any questions to the developers
labels: [ "question"]
body:
  - type: textarea
    attributes:
      label: Your question?
    validations:
      required: true